# Generated by Django 4.0 on 2022-01-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='idmessage',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
