# Generated by Django 4.0 on 2022-01-08 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0007_alter_message_idmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCache',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.room')),
            ],
        ),
    ]
