# Generated by Django 4.0.1 on 2022-01-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_roomcache_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='dm',
            field=models.BooleanField(default=False),
        ),
    ]
