# Generated by Django 4.0 on 2021-12-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='config',
            field=models.ImageField(default='pic.jpg', upload_to='profile_pics'),
        ),
    ]
