# Generated by Django 4.0 on 2021-12-30 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_online_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='offline_time',
            field=models.TimeField(default=datetime.datetime(2021, 12, 30, 16, 56, 53, 816826)),
        ),
    ]
