# Generated by Django 4.0 on 2021-12-31 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_offline_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='pic.jpg', upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='offline_time',
            field=models.TimeField(default=datetime.datetime(2021, 12, 31, 17, 20, 30, 23751)),
        ),
    ]
