# Generated by Django 4.0 on 2021-12-31 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_image'),
        ('accounts', '0004_user_image_alter_user_offline_time'),
    ]

    operations = [
    ]
