# Generated by Django 4.0 on 2022-01-06 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_offline_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='user',
            name='config',
        ),
        migrations.AlterField(
            model_name='user',
            name='offline_time',
            field=models.TimeField(default=datetime.datetime(2022, 1, 6, 18, 21, 55, 183704)),
        ),
    ]
