# Generated by Django 4.0 on 2022-01-07 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_image_user_img_remove_user_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='offline_time',
            field=models.TimeField(default=datetime.datetime(2022, 1, 7, 16, 44, 25, 352056)),
        ),
    ]
