# Generated by Django 4.0.1 on 2022-02-06 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_user_offline_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='offline_time',
            field=models.TimeField(default=datetime.datetime(2022, 2, 6, 23, 4, 1, 656783)),
        ),
    ]
